PROJECT = debris
BUILD_DEPS = geas
DEP_PLUGINS = geas

# Compile options
ERLC_OPTS = +debug_info +warn_export_all +warn_export_vars +warn_shadow_vars +warn_obsolete_guard
# Common deps for all backends
DEPS = simple_bridge eunit_formatters erlydtl debbie  

# Default backend
BACKEND=inets
# Load file 'backend.mk', if exists, to override default backend 
-include backend.mk

# Warning in top of overriden files
WARNING='%%% DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN %%%'

# Add missing dependencies depending backend
ifeq ($(BACKEND) , cowboy) 
DEPS += cowboy
endif
ifeq ($(BACKEND) , mochiweb) 
DEPS += mochiweb
endif
ifeq ($(BACKEND) , webmachine) 
DEPS += webmachine
endif
ifeq ($(BACKEND) , yaws) 
DEPS += yaws
endif

# Override some files in order to use chosen backend
$(shell echo $(WARNING) > rel/sys.config)
$(shell echo $(WARNING) > src/debris.app.src) 
$(shell echo $(WARNING) > relx.config) 
$(shell cat rel/sys.config.$(BACKEND) >> rel/sys.config)
$(shell cat src/debris.app.src.$(BACKEND) >> src/debris.app.src)
$(shell cat relx.config.$(BACKEND) >> relx.config)

include erlang.mk

clean::
	-find . -name "*~" -delete
	echo $(DEPS)

